//
//  ImjangShareRepository.swift
//  juinjang
//
//  Created by KimDongWoo on 4/26/25.
//

import RxSwift

final class ImjangShareRepository: ImjangShareRepositoryProcotol {
    func fetchShareSelectNote() -> Observable<[ImjangShareSelectModel]> {
        return Observable.just(createMockShareSelectModels())
            .delay(.milliseconds(700), scheduler: MainScheduler.instance)
    }
}

extension ImjangShareRepository {
    private func createMockShareSelectModels() -> [ImjangShareSelectModel] {
        return [
            .init(noteId: 1,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "내집",
                  imageUrl: "https://juinjangbucket.s3.ap-northeast-2.amazonaws.com/image/2536fc00-eef1-4c99-baa3-3103c49d08d8free-icon-github-logo-25231.png",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 10,
                  floor: "10",
                  shortAddress: "강남구 신사동",
                  rewardPencil: 3),
            .init(noteId: 2,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 3,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 4,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 5,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 6,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 7,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3),
            .init(noteId: 8,
                  purposeType: "RESIDENTIAL_PURPOSE",
                  propertyType: "APARTMENT",
                  priceType: "MARKET_PRICE",
                  name: "판교집",
                  imageUrl: "",
                  isScraped: false,
                  rate: 4.5,
                  price: "2200000000",
                  monthlyRent: nil,
                  pyong: 45,
                  floor: "20",
                  shortAddress: "성남시 분당구",
                  rewardPencil: 3)
        ]
    }
}
