name: AI Code Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT_FILE: ".ai/code-review/ios-review.md"
