name: Danger

on:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  danger:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Danger
        uses: danger/danger-js@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
